general_queries = [
    "what is the return policy for items purchased at our store?",
    "what is your return policy?",
    "how can I return an item?",
    "can I return an item after purchase?",
    "how long do I have to return an item?",
    "return policy for purchased items",
    "what's the return policy?",
    "return guidelines",
    "return instructions",
    "can I get a refund?",
    "how does the return process work?",
    "how do I return a product?",
    "what are the rules for returning items?",
    "how do I return something I bought?",
    "what is your store's return policy?",
    "how do I initiate a return?",
    "what is the procedure to return an item?",
    "is there a time limit for returns?",
    "can I return items I bought in-store?",
    "what steps are involved in returning a purchase?",
    "how soon can I return an item?",
    "is there a deadline for returning products?",
    "what is the process for returning a purchased item?",
    "are returns accepted for all purchases?",
    "how do I go about returning an item?",
    "can I return my purchase?",
    "what is the store policy on returns?",
    "how do returns work at your store?",
    "what are the steps for returning an item?",
    "how do I return a purchase?",
    "what do I need to do to return an item?",
    "can I return something I bought?",
    "how do I get a refund for a returned item?",
    "what is your policy on returning products?",
    "how can I find out about your return policy?",
    "what's involved in returning an item?",
    "are returns allowed for all items?",
    "how do I request a return?",
    "is there a specific process for returns?",
    "how long after purchase can I return an item?",
    "can you explain your return policy?",
    "what do I need to know about returning an item?",
    "how do I get my money back after a return?",
    "is there a return policy for your store?",
    "how do I handle returns?",
    "are there any rules for returning items?",
    "what should I do to return a product?",
    "is there a process to follow for returns?",
    "how can I return items purchased online?",
    "is it possible to return items after buying?",
    "how do I return items to your store?",
    "what is the procedure for getting a refund?",
    "can I return products bought from your store?",
    "what is required to return an item?",
    "how do returns work?",
    "can you guide me on returning items?",
    "what is your return policy for store purchases?",
    "how do I send back a purchase?"
]
exceptions_queries = [
    "are there any items that cannot be returned under this policy?",
    "non-returnable items",
    "what items cannot be returned?",
    "items not eligible for return",
    "items that cannot be refunded",
    "which items are non-returnable?",
    "return exceptions",
    "what products are excluded from returns?",
    "which items cannot be exchanged or returned?",
    "are all items returnable?",
    "what items are excluded from the return policy?",
    "are there any products that can't be returned?",
    "are there specific items I can't return?",
    "what are the return policy exceptions?",
    "are there items that cannot be exchanged?",
    "can I return all items purchased?",
    "which products have return restrictions?",
    "are some items exempt from returns?",
    "what goods are non-returnable?",
    "are any items ineligible for a refund?",
    "which items cannot be taken back?",
    "is there a list of items that can't be returned?",
    "are all products covered under the return policy?",
    "do any items have a no-return policy?",
    "can I return every item I buy?",
    "what items do not qualify for returns?",
    "are any products excluded from return eligibility?",
    "which items are not covered by the return policy?",
    "what are the exclusions to the return policy?",
    "do any items have a return exclusion?",
    "are there limitations on what can be returned?",
    "is everything eligible for a return?",
    "what are the return limitations for specific items?",
    "are there any items I cannot bring back?",
    "which items are not refundable or returnable?",
    "what are the guidelines for non-returnable items?",
    "are there return policy limitations on certain items?",
    "are any items not returnable according to the policy?",
    "which products have exceptions in the return policy?",
    "are there any restrictions on returning certain items?",
    "are some items permanently non-returnable?",
    "which products can't be returned after purchase?",
    "do any specific items have return restrictions?",
    "are there certain items not allowed to be returned?",
    "is there any product that cannot be refunded or returned?"
]

refund_queries = [
    "how will I receive my refund?",
    "refund process",
    "how do I get my refund?",
    "refund method",
    "how will my refund be processed?",
    "how do I get my money back?",
    "refund details",
    "how long does it take to get a refund?",
    "how will you refund my money?",
    "will I get my refund in cash?",
    "how will the refund be issued?",
    "how will I be reimbursed?",
    "when will I receive my refund?",
    "what is the refund procedure?",
    "will my refund go back to my credit card?",
    "what is the process to get a refund?",
    "how can I get refunded?",
    "can I receive my refund in a different method?",
    "when can I expect my refund?",
    "what steps do I need to follow for a refund?",
    "will my refund be credited to my account?",
    "what's the timeline for receiving a refund?",
    "how is the refund amount calculated?",
    "do I need to provide any documents for a refund?",
    "will my refund be processed immediately?",
    "is the refund processed through the same payment method?",
    "how do I check the status of my refund?",
    "is there a way to expedite my refund?",
    "can I choose the refund method?",
    "will I be notified when my refund is processed?",
    "how do I know if my refund request is approved?",
    "is there a fee for processing refunds?",
    "what information do I need to provide for a refund?",
    "are refunds issued on weekends?",
    "how will I be informed about the refund status?",
    "do I get a full refund or partial refund?",
    "how do you handle refunds for multiple items?",
    "is there a difference in refund time based on payment method?",
    "can I get a refund if I paid in cash?",
    "how is the refund amount determined?",
    "is there a minimum amount required for refunds?",
    "can I get a refund to a different bank account?",
    "what happens if my refund doesn't arrive?",
    "is there customer support for refund issues?"
]


human_representative_queries = [
    "i want to talk to a human",
    "i need a human representative",
    "connect me to a human",
    "i need help from a human",
    "talk to a person",
    "human representative",
    "can I speak to a human representative, please?",
    "I need to talk to a customer service agent.",
    "Can you connect me to a live person?",
    "I’d like to speak with a human representative.",
    "Please connect me to a real person.",
    "Can I talk to a human, please?",
    "I want to speak with a customer support representative.",
    "Can I get assistance from a live agent?",
    "Can you transfer me to a human representative?",
    "I need to talk to a real person.",
    "please put me through to a human representative.",
    "Can I chat with a live representative?",
    "I’d like to speak to a person in customer service.",
    "Can you get me in touch with a human agent?",
    "i need to speak with a live support agent.",
    "Please connect me with a customer service representative.",
    "Can you let me talk to a human?",
    "I need help from a real person.",
    "Can I please talk to a human representative?",
    "I’d like to communicate with a live customer service agent.",
    "Can you direct me to a human representative?",
    "I need to converse with a human agent.",
    "Is it possible to speak with a human?",
    "Please transfer my call to a person.",
    "I want to talk to a customer service agent.",
    "I need to talk to a human being.",
    "Connect me to customer support.",
    "I require human assistance.",
    "Can you get me a live person?",
    "I need to speak to someone in customer service.",
    "Please connect me to a live agent.",
    "Can I get a human on the line?",
    "I need to speak with an actual person.",
    "Can you find me a human representative?",
    "I want to talk to a person in customer support.",
    "Please let me speak with a customer service agent.",
    "I’d like to talk to a human operator.",
    "Can you transfer me to a live agent?",
    "I want to speak with someone who can help.",
    "Can I be connected to a human agent?",
    "I need a person to assist me.",
    "Please get me through to a human representative.",
    "Can I talk to a real customer service agent?",
    "I need to speak to an actual human.",
    "Can you connect me to a support agent?",
    "I want to communicate with a live person.",
    "Please transfer me to customer service.",
    "I’d like to talk to a representative.",
    "Can I have human assistance, please?",
    "I need to speak with someone in support.",
    "Please connect me to a human being.",
    "Can I get a real person to help me?",
    "I’d like to talk to someone who can assist me.",
    "Can you direct me to a live customer support agent?",
    "I need help from an actual person.",
    "Please put me in touch with a human agent.",
    "Can I talk to a live representative?",
    "I need to be transferred to a human.",
    "Please let me speak to a live agent.",
    "Can you connect me with someone who can help?",
    "I want to speak with a human customer service agent.",
    "Please transfer me to someone in customer service.",
    "Can I get connected to a human representative?",
    "I need to talk to a person in customer support.",
    "Please get me a human agent.",
    "Can you direct my call to a human?",
    "I’d like to talk to a live customer service representative.",
    "Please put me through to a real person.",
    "Can I speak with a human representative right now?",
    "I want to communicate with a customer support person.",
    "Can I get help from a human agent?",
    "Please connect me to a customer service person.",
    "I need to talk to someone in customer service, please.",
    "Can you get me a live customer service representative?",
    "I’d like to speak with a person who can assist me.",
    "Please connect me with a real person in customer support.",
    "Can I speak to a human support representative?",
    "I need assistance from a live person.",
    "Please put me in contact with a human representative."
]


order_status_queries = [
    "what is the status of my order?",
    "can you tell me my order status?",
    "i want to know the status of my order",
    "order status",
    "status of my order",
    "track my order",
    "where is my order",
    "order tracking",
    "Hi, can you tell me the status of my order?",
    "What is the current status of my recent purchase?",
    "Where is my order right now?",
    "hello, I’d like to check the status of my order.",
    "Can you update me on my order?",
    "How is my order progressing?",
    "Hi, can you provide an update on my order?",
    "Is my order on its way?",
    "Hi, when will my order arrive?",
    "What’s happening with my order?",
    "Has my order been shipped yet?",
    "Can I get a tracking update on my order?",
    "Is there any update on my order status?",
    "Please provide the status of my order.",
    "Has my order been processed?",
    "Can I check the delivery status of my order?",
    "How soon will my order be delivered?",
    "Can you tell me if my order has been dispatched?",
    "What’s the expected delivery date for my order?",
    "Can you help me find out where my order is?",
    "Could you inform me about my order status?",
    "Has my order left the warehouse?",
    "Any updates on my order?",
    "What's the ETA for my order?",
    "Is my order still being processed?",
    "Can you tell me when my order will be shipped?",
    "I need an update on my order delivery.",
    "What’s the current location of my order?",
    "Has my order been delivered yet?",
    "Can you confirm the status of my order?",
    "Where is my package now?",
    "When is my order scheduled for delivery?",
    "Can I get a progress report on my order?",
    "Is my order in transit?",
    "Can you provide details on my order shipment?",
    "What stage is my order in?",
    "Can you track my order for me?",
    "I’d like to know the whereabouts of my order.",
    "Has my order been dispatched?",
    "Can you verify the delivery status of my order?",
    "When will my order be delivered?",
    "What is the delivery status of my order?",
    "How can I track my order?",
    "Is there a way to check my order status?",
    "Can you tell me the shipping status of my order?",
    "Has my order been sent out?",
    "Can you provide me with a tracking number for my order?",
    "How can I find out where my order is?",
    "Is my order on the way?",
    "When can I expect my order to arrive?",
    "Can you check the status of my shipment?",
    "I need information on my order status.",
    "Has my package been shipped?",
    "What’s the latest on my order?",
    "Can you give me an update on my order?",
    "Has my order reached the shipping stage?",
    "What’s the progress on my order?",
    "Is there a tracking update available for my order?",
    "Can you look up my order status?",
    "Where can I track my order?",
    "Can you provide a status update on my order?",
    "Is my order out for delivery?",
    "How do I find out the status of my order?",
    "When will my package be delivered?",
    "Has my order been packed and shipped?",
    "What’s happening with my shipment?",
    "Can you tell me if my order has shipped?",
    "I need to know the current status of my order.",
    "Can you provide an update on my delivery?",
    "Has my order been received by the courier?",
    "Where is my shipment now?",
    "What’s the status of my delivery?",
    "Can I get a status update on my package?",
    "Has my order been picked up by the delivery service?",
    "How can I check the current status of my order?",
    "Is my package on its way?",
    "What’s the current shipping status of my order?",
    "When will my package arrive?",
    "Can you check on my order status for me?",
    "Has my order been logged for delivery?",
    "What’s the latest update on my order?",
    "Can you tell me if my package is in transit?",
    "How can I check if my order has been shipped?",
    "What’s the status of my recent order?",
    "Can you verify my order status?",
    "Where is my package in the delivery process?",
    "Can you provide a shipping update on my order?",
    "Has my order been marked for shipping?",
    "What’s the delivery status for my order?",
    "Can you check if my order has been dispatched?",
    "Is there any news on my order status?",
    "Can you tell me if my order is on its way?",
    "What’s the current progress of my order?",
    "Has my order been prepared for shipping?",
    "Can you give me a delivery update on my order?"
]

irrelevant_queries = [
    "asdfghjkl",
    "qwertyuiop",
    "zxcvbnm",
    "blah blah blah",
    "random text",
    "gibberish",
    "nonsense input",
    "I want chocolate pie",
    "Do you sell food?",
    "Order me a ticket to New Zealand",
    "What's the weather like today?",
    "Tell me a joke",
    "Play some music",
    "What is your favorite color?",
    "Can you dance?",
    "What time is it in Tokyo?",
    "How do I cook pasta?",
    "What's the capital of France?",
    "I need help with my homework",
    "Tell me a story",
    "Where is the nearest gas station?",
    "How old are you?",
    "Can you drive?",
    "What's the latest news?",
    "Show me a magic trick",
    "Do you like sports?",
    "What's your favorite movie?",
    "Teach me how to knit",
    "Can you swim?",
    "What is 2+2?",
    "Do you believe in aliens?",
    "How do I fix a flat tire?",
    "Can you speak Spanish?",
    "What's the meaning of life?",
    "Tell me about quantum physics",
    "I lost my keys",
    "Can you help me with my taxes?",
    "What's the best way to learn guitar?",
    "Can you write a poem?",
    "Where can I buy a good coffee?",
    "How do I get to the airport?",
    "What's the best movie of all time?",
    "Can you translate this for me?",
    "How do I bake a cake?",
    "What is your name?",
    "Can you show me cat pictures?",
    "What is love?",
    "How do I meditate?",
    "What's the stock market doing?",
    "Can you help me move?",
    "What is the airspeed velocity of an unladen swallow?",
    "How do I start a garden?",
    "Can you sing?",
    "What's the best way to travel Europe?",
    "Do you know any good books?",
    "Can you solve this riddle?",
    "What's your opinion on climate change?",
    "How do I become a millionaire?",
    "What's the best exercise for losing weight?",
    "Can you help me write a song?",
    "What's your favorite food?",
    "How do I build a website?",
    "Can you show me dog videos?",
    "What is the meaning of dreams?",
    "How do I start a podcast?",
    "What's the best way to invest money?",
    "Can you recommend a TV show?",
    "What's your favorite band?",
    "How do I train for a marathon?",
    "What's the best way to clean my house?",
    "Can you teach me to code?",
    "What's the latest fashion trend?",
    "How do I improve my memory?",
    "Can you recommend a restaurant?",
    "What is your favorite season?",
    "How do I make a smoothie?",
    "What's the best way to study?",
    "Can you help me find a job?",
    "What's the best way to relax?",
    "How do I learn a new language?",
    "Can you tell me a fun fact?",
    "What's your favorite animal?",
    "How do I fix my computer?",
    "What's the best way to save money?",
    "Can you recommend a podcast?",
    "How do I get rid of pests?",
    "What's the best way to commute?",
    "Can you tell me about space?",
    "How do I start a business?",
    "What's your favorite hobby?",
    "How do I improve my writing?",
    "Can you help me with public speaking?",
    "What's the best way to decorate a room?",
    "How do I plan a vacation?",
    "Can you help me with my resume?",
    "What's the best way to learn math?",
    "How do I deal with stress?",
    "Can you recommend a video game?",
    "What's your favorite sport?",
    "How do I start a blog?",
    "Can you help me with photography?",
    "What's the best way to cook a steak?",
    "How do I play chess?",
    "What's your opinion on technology?",
    "Can you help me with my garden?",
    "What's the best way to exercise?",
    "How do I make friends?",
    "Can you recommend a movie?",
    "What's your favorite place to travel?",
    "How do I learn to play piano?",
    "What's the best way to write a book?",
    "Can you help me with my diet?",
    "What's your favorite song?",
    "How do I fix my phone?",
    "What's the best way to shop online?",
    "Can you teach me to sew?",
    "What's your favorite TV show?"
]

# Combine and label data
all_queries = general_queries + exceptions_queries + refund_queries +human_representative_queries + order_status_queries + irrelevant_queries
labels = ["general"] * len(general_queries) + ["exceptions"] * len(exceptions_queries) + ["refund"] * len(refund_queries) + ["human"] *len(human_representative_queries) + ["order"]*len(order_status_queries) + ["nonsense"] *len(irrelevant_queries) # Adjust label assignment for augmented data
